### ISSUE TITLE
Guia de Transporte: Crear interfaz par buscar guias de transporte

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#104]
Crear interfaz par buscar guias de transporte por los campos mas comunes como numero, origen , destino,etc

**Comment by Piuliss** [comment]
esto es parecido al listar guia de transporte que ya esta? o como es?

**Comment by wildomonges** [comment]
Es parecido, el tema es que te tiene que listar solo de acuerdo a los paramteros que le pasas. Osea, buscas tienendo encuenta algunos parametros.

**Comment by Piuliss** [comment]
ok

**Comment by wildomonges** [comment]
Como va esto.?

**Comment by Piuliss** [comment]
ya termine. pero debo hacerlo mas eficiente mañana pregunto a carlos una duda que tengo

**Comment by wildomonges** [comment]
como va esto?

**Comment by Piuliss** [comment]
ya se termino.. falta hacerlo mas eficiente .. pero creo que aun no sera un problema
