### ISSUE TITLE
Producto: Permitir agregar un destinatario desde la interfaz

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#105]
Permitir agregar un destinatario desde la interfaz de nota de retiro.
Ya hay un boton + dentro de la interfaz a lado del campo para seleccionar el destinatario.

Hace un popup para crear el nuevo destinatario o redirecciona la pagina a la interfaz de destinatario. Hacelo como
te parezca mas facil.

Tiempo: 8 horas

**Comment by leois** [comment]
agregue un link, si es necesario hare un popin.
