### ISSUE TITLE
Producto: El combo direcciones se redimenciona con texto largos 

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#122]
Producto: El combo direcciones se redimenciona con texto largos 

Podes hacer que el combo tenga un tamano estatico, y que no se redimencione si es muy largo la direccion que contiene?

**Comment by Piuliss** [comment]
mmm creo que no, aunque puedo hacer algo lo arreglo y te muestro.. debe ser un select si o si?

**Comment by wildomonges** [comment]
algo que sea rapido de usar nomas.

**Comment by Piuliss** [comment]
tengo que rehacer muchos metodos. usa demasiado js.. si puedes solo mostrar el label de la tabla en los option del select y a lado un mensaje en letras pequeña la direccion (puede ser dentro de un label o un span)

**Comment by wildomonges** [comment]
ok,ok

**Comment by wildomonges** [comment]
Solucionado
