### ISSUE TITLE
Manifiesto de Carga: Permitir visualizar como pdf e imprimir

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#126]
Manifiesto de Carga: Permitir visualizar como pdf e imprimir

**Comment by Piuliss** [comment]
comienzo ha hacer esto

**Comment by wildomonges** [comment]
Como va esto?

**Comment by Piuliss** [comment]
ahora me voy a sentar a continuar .. ya cree las clases tengo que ver como quedara el pdf

**Comment by wildomonges** [comment]
Esta ya funciona?

**Comment by Piuliss** [comment]
aun no funciona esta en desarrollo.. creo que hoy ya hare una version funcional. no se si estable

**Comment by wildomonges** [comment]
para cuando la version funcional?

**Comment by Piuliss** [comment]
mañana funcionando

**Comment by Piuliss** [comment]
listo
