### ISSUE TITLE
Menu: Reubicar las posiciones de los modulos en el menu

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#129]
Menu: Reubicar las posiciones de los modulos en el menu

**Comment by wildomonges** [comment]
Podes hacer esto hoy.?

Gracias

**Comment by Piuliss** [comment]
si is

**Comment by wildomonges** [comment]
Esta noche puede estar esto?

**Comment by Piuliss** [comment]
si lo hice ayer. pero no lo de las notas (ayer recien me entere).. hoy las termino

**Comment by wildomonges** [comment]
Deja nomas como esta la parte de las notas. Me parece bien lo de administracion
Cerra nomas el issue
