### ISSUE TITLE
Guia de Transporte: Agregar Precio a cada item de la guia

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#134]
Guia de Transporte: Agregar Precio a cada item de la guia

Necesitan para calcular cuanto cobraran por cada producto que envian.

**Comment by Piuliss** [comment]
tipo nota de retiro?

**Comment by wildomonges** [comment]
ponele en cada item  entre cantidad y peso

**Comment by wildomonges** [comment]
como va esto???

**Comment by Piuliss** [comment]
mañana estara listo.

**Comment by Piuliss** [comment]
listo

**Comment by wildomonges** [comment]
Verificado
