### ISSUE TITLE
Producto: bug, al agregar seguidamente varios destinatarios nuevos

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#136]
Producto: bug, al agregar seguidamente varios destinatarios nuevos.

Cuando agrego consecutivamente  dos destinatarios nuevos desde la interfaz de producto con el popin ocurren lo siguiente:

1) El boton guardar, no cierra el popin y no guarda el destinatario.
2)Aparece en la base de datos un destinatario vacio

y Testea bien con varios receivers de seguido desde la interfaz de producto, este es el imprecindible.

**Comment by leois** [comment]
no consigo reproducir el bug. quizás por resolver el bug anterior este se resolvió también..
