### ISSUE TITLE
Guia de Transporte: Validar el numero de nota ingresada

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#140]
No debe poder ingresar texto ni numeros negativos en el campo del numero de nota

Agrega esta funcion en todos los lugares donde ingresas solo numeros:

$("#transport_guide_id").keypress(function (e)
        {
          //if the letter is not digit then display error and don't type anything
          if( e.which!=8 && e.which!=0 && (e.which<48 || e.which>57))
          {
            return false;
          }
        });

**Comment by Piuliss** [comment]
eso esta validado.. al hacer submit

**Comment by wildomonges** [comment]
Igual, es bueno tambien hacer el usuario estupido no ingrese basura del lado de cliente :)
Usa esa funcion

**Comment by Piuliss** [comment]
listo
