### ISSUE TITLE
Leo:Cambiar Password: No tengo permisos de cambiar mi password

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#143]
Leo:Cambiar Password: No tengo permisos de cambiar mi password si estoy logueado como repartidor.

Creo que el repartidor deberia de poder cambiar su password si el lo desea

**Comment by leois** [comment]
ahora todos usuarios pueden cambiar sus respectivos passwords.

**Comment by wildomonges** [comment]
Solucionado
