### ISSUE TITLE
Nota de Retiro: Testear a full con el plan de testeo

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#146]
Nota de Retiro: Testear a full con el plan de testeo

**Comment by wildomonges** [comment]
Dedicale por lo menos  3 horas

**Comment by Piuliss** [comment]
che. .sera que Leo puede hacer esta parte.. o dejarme el testeo para este fin de semana. Amin me esta por matar con un proyecto para esta semana (el viernes debe estar en producción) y tendré que dedicarle mucho tiempo extra. y casi no podre trabajar con el proyecto

**Comment by wildomonges** [comment]
Te asigno a vos leo

**Comment by leois** [comment]
okay.

2012/6/5 wildomonges <
reply@reply.github.com

> Te asigno a vos leo
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tripode/courrier/issues/146#issuecomment-6139324

## 

Leois Linka

**Comment by wildomonges** [comment]
listo
