### ISSUE TITLE
Producto: Testear a full con el plan de testeo

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#147]
Producto: Testear a full con el plan de testeo

**Comment by wildomonges** [comment]
Leo te asigno ya que raul no podra

**Comment by leois** [comment]
okay..

2012/6/5 wildomonges <
reply@reply.github.com

> Leo te asigno ya que raul no podra
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tripode/courrier/issues/147#issuecomment-6139310

## 

Leois Linka

**Comment by wildomonges** [comment]
si ya esta cerralo

**Comment by wildomonges** [comment]
esto ya esta?

**Comment by leois** [comment]
Si
