### ISSUE TITLE
Login: Me logueo aunque con el nombre del usuario en mayuscula

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#148]
Login: Me logueo aunque con el nombre del usuario en mayuscula siendo que en la base de ddatos esta en minuscula

Este error sigue leo...

**Comment by leois** [comment]
raro.. no aqui..

El 2 de junio de 2012 11:57, wildomonges <
reply@reply.github.com

> escribió:
> 
> Login: Me logueo aunque con el nombre del usuario en mayuscula siendo que
> en la base de ddatos esta en minuscula
> 
> Este error sigue leo...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tripode/courrier/issues/148

## 

Leois Linka

**Comment by leois** [comment]
voy a revisar

2012/6/3 Leois Linka leoislinka@gmail.com

> raro.. no aqui..
> 
> El 2 de junio de 2012 11:57, wildomonges <
> reply@reply.github.com
> 
> > escribió:
> 
> Login: Me logueo aunque con el nombre del usuario en mayuscula siendo que
> 
> > en la base de ddatos esta en minuscula
> > 
> > Este error sigue leo...
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/tripode/courrier/issues/148
> 
> ## 
> 
> Leois Linka

## 

Leois Linka

**Comment by leois** [comment]
este bug es cuestionable.
devise por defecto, hace un downcase antes de guardar a la base de datos
luego, al hacer login, tambien hace un downcase.

Esto es bueno por si el usuario no recuerda si ingreso UsuARio, o USuariO, o cosa asi
entonces facilita al usuario loguearse.
