### ISSUE TITLE
Testeo Notas de Retiro, Resultados

### ISSUE THREAD

**Issue by leois** [tripode/courrier#149]
- Permite guardar una nota de retiro con cantidad 0 (validacion)
- Al hacer click en limpiar se borra el campo funcionario (creo que no es necesario ese campo)
- Actualmente se puede agregar a una hoja de ruta productos pertenecientes a una nota de retiro cancelada
  (pasos: crear una nota de retiro con 5 productos, registrar 3 productos, cancelar la nota de retiro, agregar a una hoja de ruta los 3 productos registrados, creo que hay necesidad de definir eso con el cliente)

Obs.: Seguire testeando..

**Comment by wildomonges** [comment]
- Ya no se permite guardar una nota de retiro con cantidad cero
  -Se saca de la interfaz el campo funcionario

**Comment by leois** [comment]
Hi, ya puedo cerrar este issue?
El ultimo item creo que ya esta definido no?

**Comment by leois** [comment]
listo
