### ISSUE TITLE
Nota de Retiro: La fecha de registro debe ser menor a la fecha de vencimiento

### ISSUE THREAD

**Issue by leois** [tripode/courrier#157]
Creo que no deberíamos guardar una nota de retiro con una fecha
de vencimiento anterior a la fecha de registro. 
El usuario al crear tiene esta libertad de elección.

**Comment by wildomonges** [comment]
Hice que la fecha de creacion no pueda ser seleccionada por el usuario
Hice que no guarde la nota si la fecha de vencimiento es menor al de creacion

**Comment by leois** [comment]
verificado, muy bien.
