### ISSUE TITLE
Nota de Retiro: Tabla muestra notas que con diferentes estados

### ISSUE THREAD

**Issue by leois** [tripode/courrier#158]
A veces la tabla inferior muestra las notas de retiro cuyos estados no son  En proceso
Ej:
Al ingresar cualquier numero de nota de reitro y al hacer click en guardar
aparecen otras notas de retiro cuyos estados no son "en proceso"

**Comment by wildomonges** [comment]
Solucionado. No estaba filtrando correctamente al hacer create and update

**Comment by leois** [comment]
verificado
