### ISSUE TITLE
Nota de Retiro: Editar estado y datos.

### ISSUE THREAD

**Issue by leois** [tripode/courrier#159]
Un usuario solo deberia editar o cancelar una nota de retiro
solo cuando no exista un producto ya registrado para esta nota de retiro

**Comment by wildomonges** [comment]
Filtre los estados para que solo se muestre el En Proceso y Cancelado. Solo se pueden editar los en proceso, por eso tuve que dejar tambien el el combo de estados este estado.

Ahora ya no se permite editar una nota si alguno de sus productos fue registrado

**Comment by leois** [comment]
me convence, perfecto.

El 9 de junio de 2012 21:50, wildomonges <
reply@reply.github.com

> escribió:
> 
> Filtre los estados para que solo se muestre el En Proceso y Cancelado.
> Solo se pueden editar los en proceso, por eso tuve que dejar tambien el el
> combo de estados este estado.
> 
> Ahora ya no se permite editar una nota si alguno de sus productos fue
> registrado
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tripode/courrier/issues/159#issuecomment-6225263

## 

Leois Linka

**Comment by leois** [comment]
Afuera
