### ISSUE TITLE
Create Model,View,Controller:routing_sheets

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#16]
Crear el modelo vista y controlador para esta tabla. Luego se creara un issue para integrar en una vista con su detalle

**Comment by wildomonges** [comment]
Este issue estaba asignado a leo, veo que ya lo resolviste.
Cerralo si te parece

**Comment by Piuliss** [comment]
listo! falta detalles. leo anda con su tema dejemosle que lo solucione bien nomas
