### ISSUE TITLE
Producto: No guarda

### ISSUE THREAD

**Issue by leois** [tripode/courrier#162]
Pasos: 
Completar todos los campos, sin seleccionar una direccion y hacer click en guardar ==> No permite guardar
Seleccionar una direccion valida y hacer click en guardar ==> No guarda

**Comment by wildomonges** [comment]
Le saque la opcion de seleccionar si contiene direcciones, ya que le estoy seteando automaticamente una direccion por defecto

Resuelto

**Comment by leois** [comment]
verificado, es valido.
