### ISSUE TITLE
No se puede guardar al editar una hoja de ruta

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#167]
No se puede guardar al editar una hoja de ruta

El boton guardar nunca se me habilita.

**Comment by leois** [comment]
No logro reproducir este error..
El botón guardar se valida cuando seleccionas una zona y por lo menos 
debe tener un detalle (un producto)

**Comment by wildomonges** [comment]
Entra en la iterfaz para buscar una hoja de ruta.
Hace click y edita alguna que te permita, te refdirige a la pagina Editando hoja de ruta, aparece la hoja con sus detalles. EL boton guardar siempre esta disabled, aunque elimino detalles o selecciono zonas

**Comment by wildomonges** [comment]
Resuelto
