### ISSUE TITLE
Cargar Informe Hoja de Ruta: Desabilitar boton guardar por defecto

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#168]
Cargar Informe Hoja de Ruta: Desabilitar boton guardar por defecto, habilitar solo si se selecciono un numero de hoja de ruta
y si tiene detalles

**Comment by leois** [comment]
si o si debe tener un detalle, no se puede crear una hoja de ruta sin detalhes,
entonces el informe para una hoja de ruta tambien debe tenerlo..

**Comment by leois** [comment]
listo.

**Comment by wildomonges** [comment]
Perfecto
