### ISSUE TITLE
Manifiesto de Carga: Error al intentar eliminar un manifiesto

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#169]
En la lista de manifiesto , tengo la opcion de eliminar. Al hacer click en uno de ellos aparece el siguiente error:

PG::Error: ERROR:  update o delete en «cargo_manifests» viola la llave foránea «cargo_manifest_details_cargo_manifest_id_fk» en la tabla «cargo_manifest_details»
DETAIL:  La llave (id)=(1) todavía es referida desde la tabla «cargo_manifest_details».
: DELETE FROM "cargo_manifests" WHERE ("cargo_manifests"."id" = $1)

**Comment by Piuliss** [comment]
listo

**Comment by wildomonges** [comment]
Verificado
