### ISSUE TITLE
Guia de Transporte: Sacarle la opcion de editar si la GT ya fue procesada

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#173]
Esto es facil, en la lista que te trae de resultados esta la opcion para editar, lo que tenes que hacer es algo asi:

Un ejemplo en producto, para que no se muestre el link editar
<%= if product.product_state_id.to_i == ProductState.no_enviado || product.product_state_id.to_i == ProductState.extraviado then link_to image_tag('editar.gif'), edit_product_path(product) end %>

**Comment by Piuliss** [comment]
listo

**Comment by wildomonges** [comment]
Verificado
