### ISSUE TITLE
Destinatario: Error al eliminar una direccion de la lista de direcciones

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#177]
Destinatario: Erro al eliminar una direccion de la lista de direcciones.

Pasos:
1) Editar un destinataio
2)Eliminar una de sus direccion

Comportamiento optenido: Aparecio el sobre llorando.

Evita que se pueda

**Comment by leois** [comment]
done.. ya nadie llora.. jejejej

**Comment by wildomonges** [comment]
verificado
