### ISSUE TITLE
Destinatario: Error al actualizar un destinatario

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#178]
Al editar un destinatario y hacer click en actaulziar me aparece el siguiente error:

PG::Error: ERROR:  update o delete en «receiver_addresses» viola la llave foránea «products_receiver_address_id_fk» en la tabla «products»
DETAIL:  La llave (id)=(1) todavía es referida desde la tabla «products».
: DELETE FROM "receiver_addresses" WHERE ("receiver_addresses"."id" = $1)

**Comment by leois** [comment]
creo que se soluciono solo con el anterior.. aqui no reproduzco mas este error.

**Comment by wildomonges** [comment]
verificado
