### ISSUE TITLE
Buscar GT: Error al eliminar una GT procesada

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#180]
undefined method `stringify_keys' for "transport_guide_state_id":String

Al hacer click en eliminar la guia de transporte cuyo estado es procesada me lanza el error.

No debe permitirse dar la opcion de eliminar una guia de transporte que esta procesada.
Sacar el link de la imagen eliminar del sistema

Esto ocurren en el modulo Buscar

**Comment by Piuliss** [comment]
listo
