### ISSUE TITLE
Hoja de Ruta: Modificaciones requeridas al modelo impreso

### ISSUE THREAD

**Issue by leois** [tripode/courrier#187]
1- Quitar la columna item de la hoja de ruta que sera impresa
2- Agregar al final de la hoja de ruta, total de productos (o material)
3- La cabecera de informacion de la hoja de ruta no debe aparecer en todas las paginas
4- La cabecera de la tabla si debe aparecer en todas las hojas de ruta
5- Nro de pagina debe estar en la parte superior de la hoja de ruta
6- Cabecera de la tabla de hoja de ruta debe contener: Datos del Destinatario (Nombre y Apellido arriba, direccion abajo, todo en una columna), Firma, Aclaración (El espacio para aclaración debe ser mayor que el espacio para firma)
7- Quitar los bordes de la tabla

**Comment by wildomonges** [comment]
Listo
