### ISSUE TITLE
Informes de Entrega: Modificaciones requeridas

### ISSUE THREAD

**Issue by leois** [tripode/courrier#188]
1- Quitar la linea que contiene el texto "A continuación ........."
2- Quitar la linea que contiene el texto "Ds Representaciones agradece ........."
3- CADA INFORME ES POR HOJA DE RETEIRO (IMPORTANTE)
4- Modelo para la cabecera:
                                                          Informe de Entregas
Ds Representaciones
Entidad: Cooperativa Ltadda
Material: Extractos de tarjeta
Mes de: Junio 2012

Item   Código    Destinatario   Dirección    Recibido por     Devuelto por      Fecha(esto se saca de la hoja de ruta)

**Comment by leois** [comment]
puse el item 3 en mayuscula porque me pareció importante resaltar.

**Comment by wildomonges** [comment]
listo
