### ISSUE TITLE
Crear loguin

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#24]
Este sera tu tarea leo. Todo lo de seguridad.

**Comment by leois** [comment]
okay.. lo hare

2012/3/14 wildomonges <
reply@reply.github.com

> Este sera tu tarea leo. Todo lo de seguridad.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tripode/courrier/issues/24

## 

Leois Linka

**Comment by wildomonges** [comment]
Hola Leo

Podes actualizar el estado de este issue.?

Gracias

**Comment by leois** [comment]
Hola.. ya instale devise con cancan

falta arreglar los permisos y mejorar la interfaz de loggin

pueden hacer rake db:migrate

luego pueden acceder a
localhost:3000/users/sign_up, eso es para registrar un usuario, lo voy a
sacar
localhost:3000/users/sign_in, eso es el login, voy hacer un nuevo template
para esta vista.

El 29 de marzo de 2012 23:52, wildomonges <
reply@reply.github.com

> escribi:
> 
> Hola Leo
> 
> Podes actualizar el estado de este issue.?
> 
> Gracias
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tripode/courrier/issues/24#issuecomment-4835520

## 

Leois Linka

**Comment by wildomonges** [comment]
Listo. Creare otro issue para agragar permisos
