### ISSUE TITLE
Juntar en una interfaz la Guia de Transporte (Cabecera- Detalle)

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#33]
Juntar en una interfaz la Guia de Transporte (Cabecera- Detalle).
Debe tener todos los campos que tiene la maqueta de Guia de Transporte

Tiempo:3 horas

**Comment by Piuliss** [comment]
me tomara por lo menos un dia (un dia de 4 horas) mas wildo. lo siento pero es mas complicado de lo que pensaba, pero ya se como hacer. lo bueno es que cuando lo termine. el resto de las interfaces saldran falsil

**Comment by wildomonges** [comment]
No hay problema. Me parecia que era poco tiempo 3 horas. A medida que vamos avanzando tendremos mejor nocion del tiempo que nos tomara  resolver los issues.

**Comment by Piuliss** [comment]
Ya hice la interfaz funcional. Falta los estilos , validation, etc. lo marco como done por ahora wil
