### ISSUE TITLE
Aplicar Stylos css  a la interfaz Guia de Trasnporte

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#34]
Aplicar Stylos css  a la interfaz Guia de Trasnporte

Tiempo: 3 horas

**Comment by Piuliss** [comment]
veo que dividiste en dos el task.. asi creo que podre cumplir en el tiempo. .mire 3 horas y me sorprendi xD

**Comment by wildomonges** [comment]
Podes actualizar el estado de este issue.?

Gracias

**Comment by Piuliss** [comment]
listo
