### ISSUE TITLE
Crear MVC Usuarios

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#36]
Crear MVC (Modelo, Vista, Controlador) Usuarios

Tiempo: 1 hora

**Comment by wildomonges** [comment]
Leo, podes actualizar este issue.?

Gracias

**Comment by leois** [comment]
si.. hoy hare eso

2012/3/29 wildomonges <
reply@reply.github.com

> Leo, podes actualizar este issue.?
> 
> Gracias
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tripode/courrier/issues/36#issuecomment-4835474

## 

Leois Linka
