### ISSUE TITLE
Crear Pagina Principal del Sistema

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#37]
Debes incluir

1)Logo
2)Nombre de la empresa (DS Representaciones)
3)Abajo (Copyrith Trivodevs todos los derechos reservados).
4)Un fondo amigable.

En el archiv route apuntaremos a esta pagina nomas para el inicio

**Comment by Piuliss** [comment]
ahora voy a mirar partido. comienzo en una hora por ahi

**Comment by Piuliss** [comment]
cerrado
