### ISSUE TITLE
Guia de Transporte: Agregar selectores

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#40]
Agregar selector a:
Empleado: Por el momento se seleccionara con un selector, cuando este login se seteara automaticamente
Empresa
Tipo de Servicio
Forma de Pago
Tipo de Producto

Tiempo aprox: 3 Horas

**Comment by Piuliss** [comment]
Ok. tal vez haga en menos tiempo

**Comment by Piuliss** [comment]
listo
