### ISSUE TITLE
Guia de Trasporte: Crear Interfaz Manifiesto de Carga

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#49]
Manifiesto de Carga: es un documento (Informe) que se le da  la empresa que transporta los productos de una ciudad a otra.
Ver maqueta

**Comment by Piuliss** [comment]
me puedes mandar una imagen del manifiesto de carga para tener idea? o no lo tienes a mano?

**Comment by wildomonges** [comment]
Ya hice la maqueta, esta donde ponomos las imagenes de todas las maquetas

**Comment by Piuliss** [comment]
eso no se a guardar verdad? se saca para el instante? o decis para que cree unas tablas en la bd con esto y algo asi como numero de Manifiesto de carga?

**Comment by wildomonges** [comment]
Creo que no hace falta, porque es tipo un informe,

**Comment by Piuliss** [comment]
Hecho. solo falta hacer la funcion editar de la pagina listar
