### ISSUE TITLE
Guia de Transporte :  Validaciones a campos

### ISSUE THREAD

**Issue by Piuliss** [tripode/courrier#56]
Agregar Validaciones del lado del cliente  y servidor a todos los campos

**Comment by Piuliss** [comment]
listo.. alguien puede realizar algunos testing

**Comment by Piuliss** [comment]
lo de cargar products aun no tiene validacion estoy viendo como hacer... cuando la tabla esta vacia aun no me detecta

**Comment by wildomonges** [comment]
listo
