### ISSUE TITLE
Empleado: Mostrar mensaje al guardar

### ISSUE THREAD

**Issue by wildomonges** [tripode/courrier#79]
Al guardar debe mostrar un mensaje que se guardo el empleado.

Al guardar NO debe ir a la pagina show para mostrar el empleado guardado. Solo debe mostrarse un mensaje en la pagina (no en un popin) que el empleado ha sido guardado en verde.

El mensaje debe aparecer antes de la lista de empleados que se muestra en la interfaz de new empleado.

**Comment by Piuliss** [comment]
como hacen esto? para tener una idea o aun no lo hicieron?

**Comment by Piuliss** [comment]
listo!
